# ------------------------------------------------------------------------------
# 6. COLORES BASE (ESTILO OSCURO / TOKYO NIGHT ENHANCED)
# ------------------------------------------------------------------------------
background            #1a1b26
foreground            #c0caf5
selection_background  #283457
selection_foreground  #c0caf5
url_color             #73daca
cursor                #c0caf5

# Negro
color0 #15161e
color8 #414868

# Rojo
color1 #f7768e
color9 #f7768e

# Verde
color2  #73daca
color10 #73daca

# Amarillo
color3  #e0af68
color11 #e0af68

# Azul
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cian
color6  #7dcfff
color14 #7dcfff

# Blanco
color7  #a9b1d6
color15 #c0caf5
